#!/bin/python3
## Linux
# The first line is used to make the file executable as a bash script
# using the command: ./se2221 [OPTIONS] COMMAND [ARGS]...
# make it executable: chmod +x se2221
## Windows
# The first line does not affect the programm, it is treated as comment
# run script as python script: python3 se2221 [OPTIONS] COMMAND [ARGS]...

import click
import requests

baseURL = "http://127.0.0.1:9103/intelliq_api"

@click.group()
def cli():
    """CLI for Questionnaire API"""
    pass


@cli.command()
def healthcheck():
    """Check health status of server"""
    url = baseURL + "/admin/healthcheck"
    response = requests.get(url=url)
    print(response.json()) 
    pass

@cli.command()
def resetall():
    """<Replace with the command description>"""
    url = baseURL + "/admin/resetall"
    response = requests.post(url=url)
    print(response.json()) 
    pass

@cli.command()
@click.option('--source', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
def questionnaire_upd(source):
    """<Replace with the command description>"""
    pass

@cli.command()
@click.option('--questionnaire_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
def resetq(questionnaire_id):
    """<Replace with the command description>"""
    pass

#Ena
@cli.command()
@click.option('--questionnaire_id', prompt='Type the questionnaire id', help='<Replace with the option description>')
def questionnaire(questionnaire_id):
    """Print the selected questionnaire"""
    url = api_url + "/questionnaire/" + questionnaire_id
    response = requests.get(url)
    click.echo(response.text)
    pass

#Dyo
@cli.command()
@click.option('--questionnaire_id', prompt='Type the questionnaire id', help='<Replace with the option description>')
@click.option('--question_id', prompt='Type the question id', help='<Replace with the option description>')
def question(questionnaire_id, question_id):
    """Print the selected question of a questionnaire"""
    url = api_url + "/question/" + questionnaire_id + "/" + question_id
    response = requests.get(url)
    click.echo(response.text)
    pass

@cli.command()
@click.option('--questionnaire_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
@click.option('--question_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
@click.option('--session_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
@click.option('--option_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
def doanswer(questionnaire_id, question_id, session_id, option_id):
    """<Replace with the command description>"""
    pass

@cli.command()
@click.option('--questionnaire_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
@click.option('--session_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
def getsessionanswers(questionnaire_id, session_id):
    """<Replace with the command description>"""
    pass

@cli.command()
@click.option('--questionnaire_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
@click.option('--question_id', prompt='<Replace with the prompt message>', help='<Replace with the option description>')
def getquestionanswers(questionnaire_id, question_id):
    """<Replace with the command description>"""
    pass



if __name__ == '__main__':
    cli()